version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_REMOTE_INPUT_HOST=
      - NIFI_REMOTE_INPUT_PORT=
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - nifi_data:/opt/nifi/nifi-current/data
    networks:
      - nifi_network
    restart: always

volumes:
  nifi_data:
    driver: local

networks:
  nifi_network:
    driver: bridge

